services:
  bgr-sign:
    build:
      context: .
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.sign.rule=Host(`${DOMAINE_NAME}`)
      - traefik.http.routers.sign.entrypoints=web
      - traefik.http.routers.sign-secure.rule=Host(`${DOMAINE_NAME}`)
      - traefik.http.routers.sign-secure.entrypoints=websecure
      - traefik.http.routers.sign-secure.tls.certresolver=letsencrypt
      - traefik.http.services.node-api.loadbalancer.server.port=5174
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true